// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.2
// source: pay/api_pay.proto

// protobuf的package，根据业务来定，一个文件夹下的package得是一样的

package api_pay

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subject     string `protobuf:"bytes,1,opt,name=subject,proto3" form:"subject" json:"subject,omitempty" query:"subject"`                  // 订单标题
	TotalAmount string `protobuf:"bytes,2,opt,name=totalAmount,proto3" form:"totalAmount" json:"totalAmount,omitempty" query:"totalAmount"`  // 订单金额
	TradeNo     string `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" form:"trade_no" json:"trade_no,omitempty" query:"trade_no"` // 电商平台订单号
}

func (x *ApiPayReq) Reset() {
	*x = ApiPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_api_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiPayReq) ProtoMessage() {}

func (x *ApiPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_api_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiPayReq.ProtoReflect.Descriptor instead.
func (*ApiPayReq) Descriptor() ([]byte, []int) {
	return file_pay_api_pay_proto_rawDescGZIP(), []int{0}
}

func (x *ApiPayReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ApiPayReq) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *ApiPayReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type ApiPayRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                    `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`
	Msg   string                   `protobuf:"bytes,2,opt,name=msg,proto3" form:"msg" json:"msg,omitempty" query:"msg"`
	LogId string                   `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" form:"log_id" json:"log_id,omitempty" query:"log_id"`
	Data  *ApiPayRsp_ApiPayRspData `protobuf:"bytes,4,opt,name=data,proto3" form:"data" json:"data,omitempty" query:"data"`
}

func (x *ApiPayRsp) Reset() {
	*x = ApiPayRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_api_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiPayRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiPayRsp) ProtoMessage() {}

func (x *ApiPayRsp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_api_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiPayRsp.ProtoReflect.Descriptor instead.
func (*ApiPayRsp) Descriptor() ([]byte, []int) {
	return file_pay_api_pay_proto_rawDescGZIP(), []int{1}
}

func (x *ApiPayRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiPayRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApiPayRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *ApiPayRsp) GetData() *ApiPayRsp_ApiPayRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiPayRsp_ApiPayRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayUrl  string `protobuf:"bytes,1,opt,name=pay_url,json=payUrl,proto3" form:"pay_url" json:"pay_url,omitempty" query:"pay_url"`      // 支付链接
	TradeNo string `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" form:"trade_no" json:"trade_no,omitempty" query:"trade_no"` // 电商平台交易号
}

func (x *ApiPayRsp_ApiPayRspData) Reset() {
	*x = ApiPayRsp_ApiPayRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_api_pay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiPayRsp_ApiPayRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiPayRsp_ApiPayRspData) ProtoMessage() {}

func (x *ApiPayRsp_ApiPayRspData) ProtoReflect() protoreflect.Message {
	mi := &file_pay_api_pay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiPayRsp_ApiPayRspData.ProtoReflect.Descriptor instead.
func (*ApiPayRsp_ApiPayRspData) Descriptor() ([]byte, []int) {
	return file_pay_api_pay_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ApiPayRsp_ApiPayRspData) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *ApiPayRsp_ApiPayRspData) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

var File_pay_api_pay_proto protoreflect.FileDescriptor

var file_pay_api_pay_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x61, 0x79, 0x22, 0x62, 0x0a, 0x09, 0x41, 0x70, 0x69, 0x50,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0xbf, 0x01, 0x0a,
	0x09, 0x41, 0x70, 0x69, 0x50, 0x61, 0x79, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x61, 0x79, 0x2e, 0x41, 0x70, 0x69, 0x50,
	0x61, 0x79, 0x52, 0x73, 0x70, 0x2e, 0x41, 0x70, 0x69, 0x50, 0x61, 0x79, 0x52, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x43, 0x0a, 0x0d, 0x41, 0x70, 0x69,
	0x50, 0x61, 0x79, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x79,
	0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x42, 0x44,
	0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x7a, 0x6c,
	0x2d, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x5f, 0x70, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_api_pay_proto_rawDescOnce sync.Once
	file_pay_api_pay_proto_rawDescData = file_pay_api_pay_proto_rawDesc
)

func file_pay_api_pay_proto_rawDescGZIP() []byte {
	file_pay_api_pay_proto_rawDescOnce.Do(func() {
		file_pay_api_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_api_pay_proto_rawDescData)
	})
	return file_pay_api_pay_proto_rawDescData
}

var file_pay_api_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pay_api_pay_proto_goTypes = []interface{}{
	(*ApiPayReq)(nil),               // 0: pay.ApiPayReq
	(*ApiPayRsp)(nil),               // 1: pay.ApiPayRsp
	(*ApiPayRsp_ApiPayRspData)(nil), // 2: pay.ApiPayRsp.ApiPayRspData
}
var file_pay_api_pay_proto_depIdxs = []int32{
	2, // 0: pay.ApiPayRsp.data:type_name -> pay.ApiPayRsp.ApiPayRspData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pay_api_pay_proto_init() }
func file_pay_api_pay_proto_init() {
	if File_pay_api_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_api_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_api_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiPayRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_api_pay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiPayRsp_ApiPayRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_api_pay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pay_api_pay_proto_goTypes,
		DependencyIndexes: file_pay_api_pay_proto_depIdxs,
		MessageInfos:      file_pay_api_pay_proto_msgTypes,
	}.Build()
	File_pay_api_pay_proto = out.File
	file_pay_api_pay_proto_rawDesc = nil
	file_pay_api_pay_proto_goTypes = nil
	file_pay_api_pay_proto_depIdxs = nil
}
