// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: goods/goods.proto

package goods

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 根据id获取商品列表
type GetGoodsListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuIds []uint64 `protobuf:"varint,1,rep,packed,name=spu_ids,json=spuIds,proto3" json:"spu_ids,omitempty"`
}

func (x *GetGoodsListReq) Reset() {
	*x = GetGoodsListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListReq) ProtoMessage() {}

func (x *GetGoodsListReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListReq.ProtoReflect.Descriptor instead.
func (*GetGoodsListReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{0}
}

func (x *GetGoodsListReq) GetSpuIds() []uint64 {
	if x != nil {
		return x.SpuIds
	}
	return nil
}

type GetGoodsListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                               `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *GetGoodsListRsp_GetGoodsListRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetGoodsListRsp) Reset() {
	*x = GetGoodsListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListRsp) ProtoMessage() {}

func (x *GetGoodsListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListRsp.ProtoReflect.Descriptor instead.
func (*GetGoodsListRsp) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{1}
}

func (x *GetGoodsListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGoodsListRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGoodsListRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *GetGoodsListRsp) GetData() *GetGoodsListRsp_GetGoodsListRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 商品详情页
type GetGoodsDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId uint64 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
}

func (x *GetGoodsDetailReq) Reset() {
	*x = GetGoodsDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailReq) ProtoMessage() {}

func (x *GetGoodsDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailReq.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{2}
}

func (x *GetGoodsDetailReq) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

type GetGoodsDetailRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                                   `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *GetGoodsDetailRsp_GetGoodsDetailRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetGoodsDetailRsp) Reset() {
	*x = GetGoodsDetailRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsDetailRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailRsp) ProtoMessage() {}

func (x *GetGoodsDetailRsp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailRsp.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailRsp) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoodsDetailRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGoodsDetailRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGoodsDetailRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *GetGoodsDetailRsp) GetData() *GetGoodsDetailRsp_GetGoodsDetailRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 发布商品
type PublishGoodsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId   uint64 `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName string `protobuf:"bytes,2,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BrandId      uint64 `protobuf:"varint,3,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName    string `protobuf:"bytes,4,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	SpuName      string `protobuf:"bytes,5,opt,name=spu_name,json=spuName,proto3" json:"spu_name,omitempty"`
	SpuDesc      string `protobuf:"bytes,6,opt,name=spu_desc,json=spuDesc,proto3" json:"spu_desc,omitempty"`
	SpuPrice     string `protobuf:"bytes,7,opt,name=spu_price,json=spuPrice,proto3" json:"spu_price,omitempty"`
	SpuImgUrl    string `protobuf:"bytes,8,opt,name=spu_img_url,json=spuImgUrl,proto3" json:"spu_img_url,omitempty"`
	// 规格
	SkuInfoList []*PublishGoodsReq_PublishSkuInfo `protobuf:"bytes,9,rep,name=sku_info_list,json=skuInfoList,proto3" json:"sku_info_list,omitempty"`
	// 属性
	AttributeInfoList []*PublishGoodsReq_PublishAttributeInfo `protobuf:"bytes,10,rep,name=attribute_info_list,json=attributeInfoList,proto3" json:"attribute_info_list,omitempty"`
}

func (x *PublishGoodsReq) Reset() {
	*x = PublishGoodsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGoodsReq) ProtoMessage() {}

func (x *PublishGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGoodsReq.ProtoReflect.Descriptor instead.
func (*PublishGoodsReq) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{4}
}

func (x *PublishGoodsReq) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PublishGoodsReq) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *PublishGoodsReq) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *PublishGoodsReq) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *PublishGoodsReq) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *PublishGoodsReq) GetSpuDesc() string {
	if x != nil {
		return x.SpuDesc
	}
	return ""
}

func (x *PublishGoodsReq) GetSpuPrice() string {
	if x != nil {
		return x.SpuPrice
	}
	return ""
}

func (x *PublishGoodsReq) GetSpuImgUrl() string {
	if x != nil {
		return x.SpuImgUrl
	}
	return ""
}

func (x *PublishGoodsReq) GetSkuInfoList() []*PublishGoodsReq_PublishSkuInfo {
	if x != nil {
		return x.SkuInfoList
	}
	return nil
}

func (x *PublishGoodsReq) GetAttributeInfoList() []*PublishGoodsReq_PublishAttributeInfo {
	if x != nil {
		return x.AttributeInfoList
	}
	return nil
}

type PublishGoodsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                               `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *PublishGoodsRsp_PublishGoodsRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PublishGoodsRsp) Reset() {
	*x = PublishGoodsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGoodsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGoodsRsp) ProtoMessage() {}

func (x *PublishGoodsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGoodsRsp.ProtoReflect.Descriptor instead.
func (*PublishGoodsRsp) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{5}
}

func (x *PublishGoodsRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PublishGoodsRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PublishGoodsRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *PublishGoodsRsp) GetData() *PublishGoodsRsp_PublishGoodsRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetGoodsListRsp_GetGoodsListRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuList []*SpuInfo `protobuf:"bytes,1,rep,name=spu_list,json=spuList,proto3" json:"spu_list,omitempty"`
}

func (x *GetGoodsListRsp_GetGoodsListRspData) Reset() {
	*x = GetGoodsListRsp_GetGoodsListRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsListRsp_GetGoodsListRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsListRsp_GetGoodsListRspData) ProtoMessage() {}

func (x *GetGoodsListRsp_GetGoodsListRspData) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsListRsp_GetGoodsListRspData.ProtoReflect.Descriptor instead.
func (*GetGoodsListRsp_GetGoodsListRspData) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetGoodsListRsp_GetGoodsListRspData) GetSpuList() []*SpuInfo {
	if x != nil {
		return x.SpuList
	}
	return nil
}

type GetGoodsDetailRsp_GetGoodsDetailRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuInfo *SpuInfo `protobuf:"bytes,1,opt,name=spu_info,json=spuInfo,proto3" json:"spu_info,omitempty"`
}

func (x *GetGoodsDetailRsp_GetGoodsDetailRspData) Reset() {
	*x = GetGoodsDetailRsp_GetGoodsDetailRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGoodsDetailRsp_GetGoodsDetailRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoodsDetailRsp_GetGoodsDetailRspData) ProtoMessage() {}

func (x *GetGoodsDetailRsp_GetGoodsDetailRspData) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoodsDetailRsp_GetGoodsDetailRspData.ProtoReflect.Descriptor instead.
func (*GetGoodsDetailRsp_GetGoodsDetailRspData) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetGoodsDetailRsp_GetGoodsDetailRspData) GetSpuInfo() *SpuInfo {
	if x != nil {
		return x.SpuInfo
	}
	return nil
}

type PublishGoodsReq_PublishSkuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockNum     uint64          `protobuf:"varint,1,opt,name=stock_num,json=stockNum,proto3" json:"stock_num,omitempty"`
	SkuPrice     string          `protobuf:"bytes,2,opt,name=sku_price,json=skuPrice,proto3" json:"sku_price,omitempty"`
	SpecKeyValue []*SpecKeyValue `protobuf:"bytes,3,rep,name=spec_key_value,json=specKeyValue,proto3" json:"spec_key_value,omitempty"`
}

func (x *PublishGoodsReq_PublishSkuInfo) Reset() {
	*x = PublishGoodsReq_PublishSkuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGoodsReq_PublishSkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGoodsReq_PublishSkuInfo) ProtoMessage() {}

func (x *PublishGoodsReq_PublishSkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGoodsReq_PublishSkuInfo.ProtoReflect.Descriptor instead.
func (*PublishGoodsReq_PublishSkuInfo) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PublishGoodsReq_PublishSkuInfo) GetStockNum() uint64 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

func (x *PublishGoodsReq_PublishSkuInfo) GetSkuPrice() string {
	if x != nil {
		return x.SkuPrice
	}
	return ""
}

func (x *PublishGoodsReq_PublishSkuInfo) GetSpecKeyValue() []*SpecKeyValue {
	if x != nil {
		return x.SpecKeyValue
	}
	return nil
}

type PublishGoodsReq_PublishAttributeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeName  string `protobuf:"bytes,1,opt,name=attribute_name,json=attributeName,proto3" json:"attribute_name,omitempty"`
	AttributeValue string `protobuf:"bytes,2,opt,name=attribute_value,json=attributeValue,proto3" json:"attribute_value,omitempty"`
}

func (x *PublishGoodsReq_PublishAttributeInfo) Reset() {
	*x = PublishGoodsReq_PublishAttributeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGoodsReq_PublishAttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGoodsReq_PublishAttributeInfo) ProtoMessage() {}

func (x *PublishGoodsReq_PublishAttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGoodsReq_PublishAttributeInfo.ProtoReflect.Descriptor instead.
func (*PublishGoodsReq_PublishAttributeInfo) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PublishGoodsReq_PublishAttributeInfo) GetAttributeName() string {
	if x != nil {
		return x.AttributeName
	}
	return ""
}

func (x *PublishGoodsReq_PublishAttributeInfo) GetAttributeValue() string {
	if x != nil {
		return x.AttributeValue
	}
	return ""
}

type PublishGoodsRsp_PublishGoodsRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId uint64 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
}

func (x *PublishGoodsRsp_PublishGoodsRspData) Reset() {
	*x = PublishGoodsRsp_PublishGoodsRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_goods_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishGoodsRsp_PublishGoodsRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGoodsRsp_PublishGoodsRspData) ProtoMessage() {}

func (x *PublishGoodsRsp_PublishGoodsRspData) ProtoReflect() protoreflect.Message {
	mi := &file_goods_goods_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGoodsRsp_PublishGoodsRspData.ProtoReflect.Descriptor instead.
func (*PublishGoodsRsp_PublishGoodsRspData) Descriptor() ([]byte, []int) {
	return file_goods_goods_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PublishGoodsRsp_PublishGoodsRspData) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

var File_goods_goods_proto protoreflect.FileDescriptor

var file_goods_goods_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x1a, 0x12, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x04, 0x52, 0x06, 0x73, 0x70, 0x75, 0x49, 0x64, 0x73, 0x22, 0xd0, 0x01, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x40, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x53, 0x70, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x70, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2a, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x73, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x42, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x08, 0x73, 0x70, 0x75,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x53, 0x70, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x70, 0x75,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x9c, 0x05, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68,
	0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x72, 0x61,
	0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x75, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x75, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x70, 0x75, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x70, 0x75, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0b, 0x73,
	0x70, 0x75, 0x5f, 0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x70, 0x75, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x49, 0x0a, 0x0d, 0x73,
	0x6b, 0x75, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x73, 0x6b, 0x75, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x5b, 0x0a, 0x13, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x11, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x85, 0x01, 0x0a, 0x0e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x53,
	0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b,
	0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x75, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x75, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x39, 0x0a, 0x0e, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73,
	0x2e, 0x53, 0x70, 0x65, 0x63, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c, 0x73,
	0x70, 0x65, 0x63, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x66, 0x0a, 0x14, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x0f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a,
	0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x73, 0x70, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x2c, 0x0a, 0x13, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x47,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x0a, 0x06, 0x73,
	0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x70, 0x75,
	0x49, 0x64, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x7a, 0x6c, 0x2d, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68, 0x6f,
	0x70, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f,
	0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_goods_goods_proto_rawDescOnce sync.Once
	file_goods_goods_proto_rawDescData = file_goods_goods_proto_rawDesc
)

func file_goods_goods_proto_rawDescGZIP() []byte {
	file_goods_goods_proto_rawDescOnce.Do(func() {
		file_goods_goods_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_goods_proto_rawDescData)
	})
	return file_goods_goods_proto_rawDescData
}

var file_goods_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_goods_goods_proto_goTypes = []interface{}{
	(*GetGoodsListReq)(nil),                         // 0: goods.GetGoodsListReq
	(*GetGoodsListRsp)(nil),                         // 1: goods.GetGoodsListRsp
	(*GetGoodsDetailReq)(nil),                       // 2: goods.GetGoodsDetailReq
	(*GetGoodsDetailRsp)(nil),                       // 3: goods.GetGoodsDetailRsp
	(*PublishGoodsReq)(nil),                         // 4: goods.PublishGoodsReq
	(*PublishGoodsRsp)(nil),                         // 5: goods.PublishGoodsRsp
	(*GetGoodsListRsp_GetGoodsListRspData)(nil),     // 6: goods.GetGoodsListRsp.GetGoodsListRspData
	(*GetGoodsDetailRsp_GetGoodsDetailRspData)(nil), // 7: goods.GetGoodsDetailRsp.GetGoodsDetailRspData
	(*PublishGoodsReq_PublishSkuInfo)(nil),          // 8: goods.PublishGoodsReq.PublishSkuInfo
	(*PublishGoodsReq_PublishAttributeInfo)(nil),    // 9: goods.PublishGoodsReq.PublishAttributeInfo
	(*PublishGoodsRsp_PublishGoodsRspData)(nil),     // 10: goods.PublishGoodsRsp.PublishGoodsRspData
	(*SpuInfo)(nil),                                 // 11: goods.SpuInfo
	(*SpecKeyValue)(nil),                            // 12: goods.SpecKeyValue
}
var file_goods_goods_proto_depIdxs = []int32{
	6,  // 0: goods.GetGoodsListRsp.data:type_name -> goods.GetGoodsListRsp.GetGoodsListRspData
	7,  // 1: goods.GetGoodsDetailRsp.data:type_name -> goods.GetGoodsDetailRsp.GetGoodsDetailRspData
	8,  // 2: goods.PublishGoodsReq.sku_info_list:type_name -> goods.PublishGoodsReq.PublishSkuInfo
	9,  // 3: goods.PublishGoodsReq.attribute_info_list:type_name -> goods.PublishGoodsReq.PublishAttributeInfo
	10, // 4: goods.PublishGoodsRsp.data:type_name -> goods.PublishGoodsRsp.PublishGoodsRspData
	11, // 5: goods.GetGoodsListRsp.GetGoodsListRspData.spu_list:type_name -> goods.SpuInfo
	11, // 6: goods.GetGoodsDetailRsp.GetGoodsDetailRspData.spu_info:type_name -> goods.SpuInfo
	12, // 7: goods.PublishGoodsReq.PublishSkuInfo.spec_key_value:type_name -> goods.SpecKeyValue
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_goods_goods_proto_init() }
func file_goods_goods_proto_init() {
	if File_goods_goods_proto != nil {
		return
	}
	file_goods_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_goods_goods_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsDetailRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGoodsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGoodsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsListRsp_GetGoodsListRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGoodsDetailRsp_GetGoodsDetailRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGoodsReq_PublishSkuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGoodsReq_PublishAttributeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_goods_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishGoodsRsp_PublishGoodsRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_goods_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goods_goods_proto_goTypes,
		DependencyIndexes: file_goods_goods_proto_depIdxs,
		MessageInfos:      file_goods_goods_proto_msgTypes,
	}.Build()
	File_goods_goods_proto = out.File
	file_goods_goods_proto_rawDesc = nil
	file_goods_goods_proto_goTypes = nil
	file_goods_goods_proto_depIdxs = nil
}

var _ context.Context
