// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: goods/stock.proto

package goods

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 扣减库存
type StockReduceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string             `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Items   []*StockReduceItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StockReduceReq) Reset() {
	*x = StockReduceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockReduceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReduceReq) ProtoMessage() {}

func (x *StockReduceReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReduceReq.ProtoReflect.Descriptor instead.
func (*StockReduceReq) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{0}
}

func (x *StockReduceReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *StockReduceReq) GetItems() []*StockReduceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockReduceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                             `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *StockReduceRsp_StockReduceRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StockReduceRsp) Reset() {
	*x = StockReduceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockReduceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReduceRsp) ProtoMessage() {}

func (x *StockReduceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReduceRsp.ProtoReflect.Descriptor instead.
func (*StockReduceRsp) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{1}
}

func (x *StockReduceRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StockReduceRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StockReduceRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *StockReduceRsp) GetData() *StockReduceRsp_StockReduceRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 扣减库存回滚
type StockIncreaseReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string             `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Items   []*StockReduceItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *StockIncreaseReq) Reset() {
	*x = StockIncreaseReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockIncreaseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockIncreaseReq) ProtoMessage() {}

func (x *StockIncreaseReq) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockIncreaseReq.ProtoReflect.Descriptor instead.
func (*StockIncreaseReq) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{2}
}

func (x *StockIncreaseReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *StockIncreaseReq) GetItems() []*StockReduceItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type StockIncreaseRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                                 `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *StockIncreaseRsp_StockIncreaseRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StockIncreaseRsp) Reset() {
	*x = StockIncreaseRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockIncreaseRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockIncreaseRsp) ProtoMessage() {}

func (x *StockIncreaseRsp) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockIncreaseRsp.ProtoReflect.Descriptor instead.
func (*StockIncreaseRsp) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{3}
}

func (x *StockIncreaseRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StockIncreaseRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StockIncreaseRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *StockIncreaseRsp) GetData() *StockIncreaseRsp_StockIncreaseRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StockReduceItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId    uint64 `protobuf:"varint,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	StockNum int32  `protobuf:"varint,2,opt,name=stock_num,json=stockNum,proto3" json:"stock_num,omitempty"`
}

func (x *StockReduceItem) Reset() {
	*x = StockReduceItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockReduceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReduceItem) ProtoMessage() {}

func (x *StockReduceItem) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReduceItem.ProtoReflect.Descriptor instead.
func (*StockReduceItem) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{4}
}

func (x *StockReduceItem) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *StockReduceItem) GetStockNum() int32 {
	if x != nil {
		return x.StockNum
	}
	return 0
}

type StockReduceRsp_StockReduceRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StockReduceRsp_StockReduceRspData) Reset() {
	*x = StockReduceRsp_StockReduceRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockReduceRsp_StockReduceRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReduceRsp_StockReduceRspData) ProtoMessage() {}

func (x *StockReduceRsp_StockReduceRspData) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReduceRsp_StockReduceRspData.ProtoReflect.Descriptor instead.
func (*StockReduceRsp_StockReduceRspData) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{1, 0}
}

type StockIncreaseRsp_StockIncreaseRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StockIncreaseRsp_StockIncreaseRspData) Reset() {
	*x = StockIncreaseRsp_StockIncreaseRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goods_stock_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockIncreaseRsp_StockIncreaseRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockIncreaseRsp_StockIncreaseRspData) ProtoMessage() {}

func (x *StockIncreaseRsp_StockIncreaseRspData) ProtoReflect() protoreflect.Message {
	mi := &file_goods_stock_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockIncreaseRsp_StockIncreaseRspData.ProtoReflect.Descriptor instead.
func (*StockIncreaseRsp_StockIncreaseRspData) Descriptor() ([]byte, []int) {
	return file_goods_stock_proto_rawDescGZIP(), []int{3, 0}
}

var File_goods_stock_proto protoreflect.FileDescriptor

var file_goods_stock_proto_rawDesc = []byte{
	0x0a, 0x11, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x1a, 0x12, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59,
	0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x2c, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa1, 0x01, 0x0a, 0x0e, 0x53, 0x74,
	0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x73, 0x70, 0x2e, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x14, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a,
	0x10, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x2c, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x64, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x64, 0x75, 0x63, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x10, 0x53,
	0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x40, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67, 0x6f, 0x6f,
	0x64, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65,
	0x52, 0x73, 0x70, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73,
	0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x16,
	0x0a, 0x14, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x52,
	0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x22, 0x45, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x52,
	0x65, 0x64, 0x75, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x6b, 0x75,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x6b, 0x75, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x42, 0x35, 0x5a,
	0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x7a, 0x6c, 0x2d,
	0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x67,
	0x6f, 0x6f, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goods_stock_proto_rawDescOnce sync.Once
	file_goods_stock_proto_rawDescData = file_goods_stock_proto_rawDesc
)

func file_goods_stock_proto_rawDescGZIP() []byte {
	file_goods_stock_proto_rawDescOnce.Do(func() {
		file_goods_stock_proto_rawDescData = protoimpl.X.CompressGZIP(file_goods_stock_proto_rawDescData)
	})
	return file_goods_stock_proto_rawDescData
}

var file_goods_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_goods_stock_proto_goTypes = []interface{}{
	(*StockReduceReq)(nil),                        // 0: goods.StockReduceReq
	(*StockReduceRsp)(nil),                        // 1: goods.StockReduceRsp
	(*StockIncreaseReq)(nil),                      // 2: goods.StockIncreaseReq
	(*StockIncreaseRsp)(nil),                      // 3: goods.StockIncreaseRsp
	(*StockReduceItem)(nil),                       // 4: goods.StockReduceItem
	(*StockReduceRsp_StockReduceRspData)(nil),     // 5: goods.StockReduceRsp.StockReduceRspData
	(*StockIncreaseRsp_StockIncreaseRspData)(nil), // 6: goods.StockIncreaseRsp.StockIncreaseRspData
}
var file_goods_stock_proto_depIdxs = []int32{
	4, // 0: goods.StockReduceReq.items:type_name -> goods.StockReduceItem
	5, // 1: goods.StockReduceRsp.data:type_name -> goods.StockReduceRsp.StockReduceRspData
	4, // 2: goods.StockIncreaseReq.items:type_name -> goods.StockReduceItem
	6, // 3: goods.StockIncreaseRsp.data:type_name -> goods.StockIncreaseRsp.StockIncreaseRspData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_goods_stock_proto_init() }
func file_goods_stock_proto_init() {
	if File_goods_stock_proto != nil {
		return
	}
	file_goods_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_goods_stock_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockReduceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockReduceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockIncreaseReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockIncreaseRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockReduceItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockReduceRsp_StockReduceRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_goods_stock_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockIncreaseRsp_StockIncreaseRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goods_stock_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goods_stock_proto_goTypes,
		DependencyIndexes: file_goods_stock_proto_depIdxs,
		MessageInfos:      file_goods_stock_proto_msgTypes,
	}.Build()
	File_goods_stock_proto = out.File
	file_goods_stock_proto_rawDesc = nil
	file_goods_stock_proto_goTypes = nil
	file_goods_stock_proto_depIdxs = nil
}

var _ context.Context
