// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _canceltradeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtradeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paycanceltoorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paysuccesstoorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _retradeMw() []app.HandlerFunc {
	// your code...
	return nil
}
