// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: order/create_trade.proto

package order

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 下单相关
type CreateTradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string                    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TradeInfo *CreateTradeReq_TradeInfo `protobuf:"bytes,2,opt,name=trade_info,json=tradeInfo,proto3" json:"trade_info,omitempty"`
	PayType   string                    `protobuf:"bytes,3,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
}

func (x *CreateTradeReq) Reset() {
	*x = CreateTradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReq) ProtoMessage() {}

func (x *CreateTradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReq.ProtoReflect.Descriptor instead.
func (*CreateTradeReq) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTradeReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTradeReq) GetTradeInfo() *CreateTradeReq_TradeInfo {
	if x != nil {
		return x.TradeInfo
	}
	return nil
}

func (x *CreateTradeReq) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

type CreateTradeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                             `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *CreateTradeRsp_CreateTradeRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateTradeRsp) Reset() {
	*x = CreateTradeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRsp) ProtoMessage() {}

func (x *CreateTradeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRsp.ProtoReflect.Descriptor instead.
func (*CreateTradeRsp) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTradeRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTradeRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateTradeRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *CreateTradeRsp) GetData() *CreateTradeRsp_CreateTradeRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTradeReq_TradeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderInfoList []*CreateTradeReq_OrderInfo `protobuf:"bytes,1,rep,name=order_info_list,json=orderInfoList,proto3" json:"order_info_list,omitempty"`
	TradeAmount   string                      `protobuf:"bytes,2,opt,name=trade_amount,json=tradeAmount,proto3" json:"trade_amount,omitempty"`
}

func (x *CreateTradeReq_TradeInfo) Reset() {
	*x = CreateTradeReq_TradeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeReq_TradeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReq_TradeInfo) ProtoMessage() {}

func (x *CreateTradeReq_TradeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReq_TradeInfo.ProtoReflect.Descriptor instead.
func (*CreateTradeReq_TradeInfo) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateTradeReq_TradeInfo) GetOrderInfoList() []*CreateTradeReq_OrderInfo {
	if x != nil {
		return x.OrderInfoList
	}
	return nil
}

func (x *CreateTradeReq_TradeInfo) GetTradeAmount() string {
	if x != nil {
		return x.TradeAmount
	}
	return ""
}

type CreateTradeReq_OrderInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuList     []*CreateTradeReq_SkuInfo `protobuf:"bytes,1,rep,name=sku_list,json=skuList,proto3" json:"sku_list,omitempty"`
	ShopId      uint64                    `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	OrderAmount string                    `protobuf:"bytes,3,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	SellerId    uint64                    `protobuf:"varint,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	BuyerId     uint64                    `protobuf:"varint,5,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
}

func (x *CreateTradeReq_OrderInfo) Reset() {
	*x = CreateTradeReq_OrderInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeReq_OrderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReq_OrderInfo) ProtoMessage() {}

func (x *CreateTradeReq_OrderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReq_OrderInfo.ProtoReflect.Descriptor instead.
func (*CreateTradeReq_OrderInfo) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateTradeReq_OrderInfo) GetSkuList() []*CreateTradeReq_SkuInfo {
	if x != nil {
		return x.SkuList
	}
	return nil
}

func (x *CreateTradeReq_OrderInfo) GetShopId() uint64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *CreateTradeReq_OrderInfo) GetOrderAmount() string {
	if x != nil {
		return x.OrderAmount
	}
	return ""
}

func (x *CreateTradeReq_OrderInfo) GetSellerId() uint64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateTradeReq_OrderInfo) GetBuyerId() uint64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

type CreateTradeReq_SkuInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpuId        uint64 `protobuf:"varint,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	SkuId        uint64 `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuName      string `protobuf:"bytes,3,opt,name=spu_name,json=spuName,proto3" json:"spu_name,omitempty"`
	CategoryId   uint64 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName string `protobuf:"bytes,5,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BrandId      uint64 `protobuf:"varint,6,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName    string `protobuf:"bytes,7,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	SkuImgUrl    string `protobuf:"bytes,8,opt,name=sku_img_url,json=skuImgUrl,proto3" json:"sku_img_url,omitempty"`
	SkuAmount    string `protobuf:"bytes,9,opt,name=sku_amount,json=skuAmount,proto3" json:"sku_amount,omitempty"`
	SpecValues   string `protobuf:"bytes,10,opt,name=spec_values,json=specValues,proto3" json:"spec_values,omitempty"` // 规格信息，json
}

func (x *CreateTradeReq_SkuInfo) Reset() {
	*x = CreateTradeReq_SkuInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeReq_SkuInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReq_SkuInfo) ProtoMessage() {}

func (x *CreateTradeReq_SkuInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReq_SkuInfo.ProtoReflect.Descriptor instead.
func (*CreateTradeReq_SkuInfo) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CreateTradeReq_SkuInfo) GetSpuId() uint64 {
	if x != nil {
		return x.SpuId
	}
	return 0
}

func (x *CreateTradeReq_SkuInfo) GetSkuId() uint64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *CreateTradeReq_SkuInfo) GetSpuName() string {
	if x != nil {
		return x.SpuName
	}
	return ""
}

func (x *CreateTradeReq_SkuInfo) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateTradeReq_SkuInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *CreateTradeReq_SkuInfo) GetBrandId() uint64 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *CreateTradeReq_SkuInfo) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *CreateTradeReq_SkuInfo) GetSkuImgUrl() string {
	if x != nil {
		return x.SkuImgUrl
	}
	return ""
}

func (x *CreateTradeReq_SkuInfo) GetSkuAmount() string {
	if x != nil {
		return x.SkuAmount
	}
	return ""
}

func (x *CreateTradeReq_SkuInfo) GetSpecValues() string {
	if x != nil {
		return x.SpecValues
	}
	return ""
}

type CreateTradeRsp_CreateTradeRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo    string `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"` // 电商交易号
	PayPageUrl string `protobuf:"bytes,2,opt,name=pay_page_url,json=payPageUrl,proto3" json:"pay_page_url,omitempty"`
}

func (x *CreateTradeRsp_CreateTradeRspData) Reset() {
	*x = CreateTradeRsp_CreateTradeRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_create_trade_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeRsp_CreateTradeRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRsp_CreateTradeRspData) ProtoMessage() {}

func (x *CreateTradeRsp_CreateTradeRspData) ProtoReflect() protoreflect.Message {
	mi := &file_order_create_trade_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRsp_CreateTradeRspData.ProtoReflect.Descriptor instead.
func (*CreateTradeRsp_CreateTradeRspData) Descriptor() ([]byte, []int) {
	return file_order_create_trade_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateTradeRsp_CreateTradeRspData) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *CreateTradeRsp_CreateTradeRspData) GetPayPageUrl() string {
	if x != nil {
		return x.PayPageUrl
	}
	return ""
}

var File_order_create_trade_proto protoreflect.FileDescriptor

var file_order_create_trade_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0xeb, 0x05, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3e, 0x0a, 0x0a, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61,
	0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x77, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x47, 0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x1a, 0xb9,
	0x01, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a, 0x08,
	0x73, 0x6b, 0x75, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x53, 0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73,
	0x6b, 0x75, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x68, 0x6f, 0x70, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x62, 0x75, 0x79, 0x65, 0x72, 0x49, 0x64, 0x1a, 0xb2, 0x02, 0x0a, 0x07, 0x53,
	0x6b, 0x75, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x70, 0x75, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x70, 0x75, 0x49, 0x64, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x6b, 0x75, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x70, 0x75, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x70, 0x75, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0b, 0x73, 0x6b, 0x75, 0x5f, 0x69, 0x6d, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6b, 0x75, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x6b, 0x75, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6b, 0x75, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x70, 0x65, 0x63, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x70, 0x65, 0x63, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22,
	0xde, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12,
	0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64,
	0x65, 0x52, 0x73, 0x70, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x51, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x12, 0x20,
	0x0a, 0x0c, 0x70, 0x61, 0x79, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x79, 0x50, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x7a, 0x6c, 0x2d, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70, 0x2d,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65,
	0x6e, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_create_trade_proto_rawDescOnce sync.Once
	file_order_create_trade_proto_rawDescData = file_order_create_trade_proto_rawDesc
)

func file_order_create_trade_proto_rawDescGZIP() []byte {
	file_order_create_trade_proto_rawDescOnce.Do(func() {
		file_order_create_trade_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_create_trade_proto_rawDescData)
	})
	return file_order_create_trade_proto_rawDescData
}

var file_order_create_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_create_trade_proto_goTypes = []interface{}{
	(*CreateTradeReq)(nil),                    // 0: order.CreateTradeReq
	(*CreateTradeRsp)(nil),                    // 1: order.CreateTradeRsp
	(*CreateTradeReq_TradeInfo)(nil),          // 2: order.CreateTradeReq.TradeInfo
	(*CreateTradeReq_OrderInfo)(nil),          // 3: order.CreateTradeReq.OrderInfo
	(*CreateTradeReq_SkuInfo)(nil),            // 4: order.CreateTradeReq.SkuInfo
	(*CreateTradeRsp_CreateTradeRspData)(nil), // 5: order.CreateTradeRsp.CreateTradeRspData
}
var file_order_create_trade_proto_depIdxs = []int32{
	2, // 0: order.CreateTradeReq.trade_info:type_name -> order.CreateTradeReq.TradeInfo
	5, // 1: order.CreateTradeRsp.data:type_name -> order.CreateTradeRsp.CreateTradeRspData
	3, // 2: order.CreateTradeReq.TradeInfo.order_info_list:type_name -> order.CreateTradeReq.OrderInfo
	4, // 3: order.CreateTradeReq.OrderInfo.sku_list:type_name -> order.CreateTradeReq.SkuInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_create_trade_proto_init() }
func file_order_create_trade_proto_init() {
	if File_order_create_trade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_create_trade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_create_trade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_create_trade_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeReq_TradeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_create_trade_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeReq_OrderInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_create_trade_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeReq_SkuInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_create_trade_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeRsp_CreateTradeRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_create_trade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_create_trade_proto_goTypes,
		DependencyIndexes: file_order_create_trade_proto_depIdxs,
		MessageInfos:      file_order_create_trade_proto_msgTypes,
	}.Build()
	File_order_create_trade_proto = out.File
	file_order_create_trade_proto_rawDesc = nil
	file_order_create_trade_proto_goTypes = nil
	file_order_create_trade_proto_depIdxs = nil
}

var _ context.Context
