// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.2
// source: api_goods/cart.proto

package api_goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToCartReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddToCartReq) Reset() {
	*x = AddToCartReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_goods_cart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartReq) ProtoMessage() {}

func (x *AddToCartReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_cart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartReq.ProtoReflect.Descriptor instead.
func (*AddToCartReq) Descriptor() ([]byte, []int) {
	return file_api_goods_cart_proto_rawDescGZIP(), []int{0}
}

type AddToCartRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                          `protobuf:"varint,1,opt,name=code,proto3" form:"code" json:"code,omitempty" query:"code"`
	Msg   string                         `protobuf:"bytes,2,opt,name=msg,proto3" form:"msg" json:"msg,omitempty" query:"msg"`
	LogId string                         `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" form:"log_id" json:"log_id,omitempty" query:"log_id"`
	Data  *AddToCartRsp_AddToCartRspData `protobuf:"bytes,4,opt,name=data,proto3" form:"data" json:"data,omitempty" query:"data"`
}

func (x *AddToCartRsp) Reset() {
	*x = AddToCartRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_goods_cart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRsp) ProtoMessage() {}

func (x *AddToCartRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_cart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRsp.ProtoReflect.Descriptor instead.
func (*AddToCartRsp) Descriptor() ([]byte, []int) {
	return file_api_goods_cart_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddToCartRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddToCartRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *AddToCartRsp) GetData() *AddToCartRsp_AddToCartRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddToCartRsp_AddToCartRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddToCartRsp_AddToCartRspData) Reset() {
	*x = AddToCartRsp_AddToCartRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_goods_cart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddToCartRsp_AddToCartRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRsp_AddToCartRspData) ProtoMessage() {}

func (x *AddToCartRsp_AddToCartRspData) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_cart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRsp_AddToCartRspData.ProtoReflect.Descriptor instead.
func (*AddToCartRsp_AddToCartRspData) Descriptor() ([]byte, []int) {
	return file_api_goods_cart_proto_rawDescGZIP(), []int{1, 0}
}

var File_api_goods_cart_proto protoreflect.FileDescriptor

var file_api_goods_cart_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x6f, 0x6f, 0x64,
	0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x71, 0x22, 0x9d, 0x01, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12,
	0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x61, 0x70, 0x69, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43,
	0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x7a, 0x6c, 0x2d, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68, 0x6f, 0x70,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f,
	0x61, 0x70, 0x69, 0x5f, 0x67, 0x6f, 0x6f, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_goods_cart_proto_rawDescOnce sync.Once
	file_api_goods_cart_proto_rawDescData = file_api_goods_cart_proto_rawDesc
)

func file_api_goods_cart_proto_rawDescGZIP() []byte {
	file_api_goods_cart_proto_rawDescOnce.Do(func() {
		file_api_goods_cart_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_goods_cart_proto_rawDescData)
	})
	return file_api_goods_cart_proto_rawDescData
}

var file_api_goods_cart_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_goods_cart_proto_goTypes = []interface{}{
	(*AddToCartReq)(nil),                  // 0: api_goods.AddToCartReq
	(*AddToCartRsp)(nil),                  // 1: api_goods.AddToCartRsp
	(*AddToCartRsp_AddToCartRspData)(nil), // 2: api_goods.AddToCartRsp.AddToCartRspData
}
var file_api_goods_cart_proto_depIdxs = []int32{
	2, // 0: api_goods.AddToCartRsp.data:type_name -> api_goods.AddToCartRsp.AddToCartRspData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_goods_cart_proto_init() }
func file_api_goods_cart_proto_init() {
	if File_api_goods_cart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_goods_cart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_goods_cart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_goods_cart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddToCartRsp_AddToCartRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_goods_cart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_goods_cart_proto_goTypes,
		DependencyIndexes: file_api_goods_cart_proto_depIdxs,
		MessageInfos:      file_api_goods_cart_proto_msgTypes,
	}.Build()
	File_api_goods_cart_proto = out.File
	file_api_goods_cart_proto_rawDesc = nil
	file_api_goods_cart_proto_goTypes = nil
	file_api_goods_cart_proto_depIdxs = nil
}
