// Code generated by hertz generator.

package goods

import (
	"github.com/cloudwego/hertz/pkg/app/client"
	"github.com/cloudwego/hertz/pkg/common/config"
)

type GoodsServiceClient struct {
	client *client.Client
}

func NewGoodsServiceClient(opt ...config.ClientOption) (*GoodsServiceClient, error) {
	c, err := client.NewClient(opt...)
	if err != nil {
		return nil, err
	}

	return &GoodsServiceClient{
		client: c,
	}, nil
}
