// Code generated by Kitex v0.12.1. DO NOT EDIT.

package exampleservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	example "github.com/lzl-here/bt-shop-backend/kitex_gen/example"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PingPong": kitex.NewMethodInfo(
		pingPongHandler,
		newPingPongArgs,
		newPingPongResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"GetPerson": kitex.NewMethodInfo(
		getPersonHandler,
		newGetPersonArgs,
		newGetPersonResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	exampleServiceServiceInfo                = NewServiceInfo()
	exampleServiceServiceInfoForClient       = NewServiceInfoForClient()
	exampleServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return exampleServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return exampleServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return exampleServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "ExampleService"
	handlerType := (*example.ExampleService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "example",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func pingPongHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(example.PingReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(example.ExampleService).PingPong(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PingPongArgs:
		success, err := handler.(example.ExampleService).PingPong(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PingPongResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPingPongArgs() interface{} {
	return &PingPongArgs{}
}

func newPingPongResult() interface{} {
	return &PingPongResult{}
}

type PingPongArgs struct {
	Req *example.PingReq
}

func (p *PingPongArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(example.PingReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PingPongArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PingPongArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PingPongArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PingPongArgs) Unmarshal(in []byte) error {
	msg := new(example.PingReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PingPongArgs_Req_DEFAULT *example.PingReq

func (p *PingPongArgs) GetReq() *example.PingReq {
	if !p.IsSetReq() {
		return PingPongArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PingPongArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PingPongArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PingPongResult struct {
	Success *example.PingRsp
}

var PingPongResult_Success_DEFAULT *example.PingRsp

func (p *PingPongResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(example.PingRsp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PingPongResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PingPongResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PingPongResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PingPongResult) Unmarshal(in []byte) error {
	msg := new(example.PingRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PingPongResult) GetSuccess() *example.PingRsp {
	if !p.IsSetSuccess() {
		return PingPongResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PingPongResult) SetSuccess(x interface{}) {
	p.Success = x.(*example.PingRsp)
}

func (p *PingPongResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PingPongResult) GetResult() interface{} {
	return p.Success
}

func getPersonHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(example.GetPersonReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(example.ExampleService).GetPerson(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPersonArgs:
		success, err := handler.(example.ExampleService).GetPerson(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPersonResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPersonArgs() interface{} {
	return &GetPersonArgs{}
}

func newGetPersonResult() interface{} {
	return &GetPersonResult{}
}

type GetPersonArgs struct {
	Req *example.GetPersonReq
}

func (p *GetPersonArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(example.GetPersonReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetPersonArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetPersonArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetPersonArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPersonArgs) Unmarshal(in []byte) error {
	msg := new(example.GetPersonReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPersonArgs_Req_DEFAULT *example.GetPersonReq

func (p *GetPersonArgs) GetReq() *example.GetPersonReq {
	if !p.IsSetReq() {
		return GetPersonArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPersonArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPersonArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPersonResult struct {
	Success *example.GetPersonRsp
}

var GetPersonResult_Success_DEFAULT *example.GetPersonRsp

func (p *GetPersonResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(example.GetPersonRsp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetPersonResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetPersonResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetPersonResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPersonResult) Unmarshal(in []byte) error {
	msg := new(example.GetPersonRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPersonResult) GetSuccess() *example.GetPersonRsp {
	if !p.IsSetSuccess() {
		return GetPersonResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPersonResult) SetSuccess(x interface{}) {
	p.Success = x.(*example.GetPersonRsp)
}

func (p *GetPersonResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPersonResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PingPong(ctx context.Context, Req *example.PingReq) (r *example.PingRsp, err error) {
	var _args PingPongArgs
	_args.Req = Req
	var _result PingPongResult
	if err = p.c.Call(ctx, "PingPong", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPerson(ctx context.Context, Req *example.GetPersonReq) (r *example.GetPersonRsp, err error) {
	var _args GetPersonArgs
	_args.Req = Req
	var _result GetPersonResult
	if err = p.c.Call(ctx, "GetPerson", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
