// Code generated by hertz generator.

package goods

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _goodsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addtocartMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getbrandlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getcategorylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgoodsdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getgoodslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getkeyworddownlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishgoodsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchspulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stockincreaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stockreduceMw() []app.HandlerFunc {
	// your code...
	return nil
}
