// Code generated by Kitex v0.12.1. DO NOT EDIT.

package personservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	person "github.com/lzl-here/bt-shop-backend/kitex_gen/person"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetPersonInfo": kitex.NewMethodInfo(
		getPersonInfoHandler,
		newGetPersonInfoArgs,
		newGetPersonInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	personServiceServiceInfo                = NewServiceInfo()
	personServiceServiceInfoForClient       = NewServiceInfoForClient()
	personServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return personServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return personServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return personServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PersonService"
	handlerType := (*person.PersonService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "person",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func getPersonInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(person.GetPersonReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(person.PersonService).GetPersonInfo(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetPersonInfoArgs:
		success, err := handler.(person.PersonService).GetPersonInfo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetPersonInfoResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetPersonInfoArgs() interface{} {
	return &GetPersonInfoArgs{}
}

func newGetPersonInfoResult() interface{} {
	return &GetPersonInfoResult{}
}

type GetPersonInfoArgs struct {
	Req *person.GetPersonReq
}

func (p *GetPersonInfoArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(person.GetPersonReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetPersonInfoArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetPersonInfoArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetPersonInfoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetPersonInfoArgs) Unmarshal(in []byte) error {
	msg := new(person.GetPersonReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetPersonInfoArgs_Req_DEFAULT *person.GetPersonReq

func (p *GetPersonInfoArgs) GetReq() *person.GetPersonReq {
	if !p.IsSetReq() {
		return GetPersonInfoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetPersonInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetPersonInfoArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetPersonInfoResult struct {
	Success *person.GetPersonRsp
}

var GetPersonInfoResult_Success_DEFAULT *person.GetPersonRsp

func (p *GetPersonInfoResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(person.GetPersonRsp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetPersonInfoResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetPersonInfoResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetPersonInfoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetPersonInfoResult) Unmarshal(in []byte) error {
	msg := new(person.GetPersonRsp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetPersonInfoResult) GetSuccess() *person.GetPersonRsp {
	if !p.IsSetSuccess() {
		return GetPersonInfoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetPersonInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*person.GetPersonRsp)
}

func (p *GetPersonInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetPersonInfoResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetPersonInfo(ctx context.Context, Req *person.GetPersonReq) (r *person.GetPersonRsp, err error) {
	var _args GetPersonInfoArgs
	_args.Req = Req
	var _result GetPersonInfoResult
	if err = p.c.Call(ctx, "GetPersonInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
