// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: order/trade.proto

package order

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trade     *BaseTrade    `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	OrderList []*TradeOrder `protobuf:"bytes,2,rep,name=order_list,json=orderList,proto3" json:"order_list,omitempty"`
}

func (x *TradeTrade) Reset() {
	*x = TradeTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeTrade) ProtoMessage() {}

func (x *TradeTrade) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeTrade.ProtoReflect.Descriptor instead.
func (*TradeTrade) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{0}
}

func (x *TradeTrade) GetTrade() *BaseTrade {
	if x != nil {
		return x.Trade
	}
	return nil
}

func (x *TradeTrade) GetOrderList() []*TradeOrder {
	if x != nil {
		return x.OrderList
	}
	return nil
}

type TradeOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order         *BaseOrder       `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	OrderItemList []*BaseOrderItem `protobuf:"bytes,2,rep,name=order_item_list,json=orderItemList,proto3" json:"order_item_list,omitempty"`
}

func (x *TradeOrder) Reset() {
	*x = TradeOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeOrder) ProtoMessage() {}

func (x *TradeOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeOrder.ProtoReflect.Descriptor instead.
func (*TradeOrder) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{1}
}

func (x *TradeOrder) GetOrder() *BaseOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *TradeOrder) GetOrderItemList() []*BaseOrderItem {
	if x != nil {
		return x.OrderItemList
	}
	return nil
}

// 创建交易
type CreateTradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Trade *TradeTrade `protobuf:"bytes,2,opt,name=trade,proto3" json:"trade,omitempty"`
}

func (x *CreateTradeReq) Reset() {
	*x = CreateTradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeReq) ProtoMessage() {}

func (x *CreateTradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeReq.ProtoReflect.Descriptor instead.
func (*CreateTradeReq) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTradeReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTradeReq) GetTrade() *TradeTrade {
	if x != nil {
		return x.Trade
	}
	return nil
}

type CreateTradeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                             `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *CreateTradeRsp_CreateTradeRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateTradeRsp) Reset() {
	*x = CreateTradeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRsp) ProtoMessage() {}

func (x *CreateTradeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRsp.ProtoReflect.Descriptor instead.
func (*CreateTradeRsp) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTradeRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTradeRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateTradeRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *CreateTradeRsp) GetData() *CreateTradeRsp_CreateTradeRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 取消交易
type CancelTradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
}

func (x *CancelTradeReq) Reset() {
	*x = CancelTradeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeReq) ProtoMessage() {}

func (x *CancelTradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeReq.ProtoReflect.Descriptor instead.
func (*CancelTradeReq) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{4}
}

func (x *CancelTradeReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type CancelTradeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                              `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                             `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                             `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *CancelTradeRsp_CancelTradeRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CancelTradeRsp) Reset() {
	*x = CancelTradeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTradeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeRsp) ProtoMessage() {}

func (x *CancelTradeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeRsp.ProtoReflect.Descriptor instead.
func (*CancelTradeRsp) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{5}
}

func (x *CancelTradeRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelTradeRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CancelTradeRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *CancelTradeRsp) GetData() *CancelTradeRsp_CancelTradeRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 查询交易列表
type GetTradeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTradeListReq) Reset() {
	*x = GetTradeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTradeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeListReq) ProtoMessage() {}

func (x *GetTradeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeListReq.ProtoReflect.Descriptor instead.
func (*GetTradeListReq) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{6}
}

type GetTradeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int32                                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg   string                               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	LogId string                               `protobuf:"bytes,3,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Data  *GetTradeListRsp_GetTradeListRspData `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTradeListRsp) Reset() {
	*x = GetTradeListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTradeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeListRsp) ProtoMessage() {}

func (x *GetTradeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeListRsp.ProtoReflect.Descriptor instead.
func (*GetTradeListRsp) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{7}
}

func (x *GetTradeListRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetTradeListRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetTradeListRsp) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *GetTradeListRsp) GetData() *GetTradeListRsp_GetTradeListRspData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateTradeRsp_CreateTradeRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"` // 电商交易号
}

func (x *CreateTradeRsp_CreateTradeRspData) Reset() {
	*x = CreateTradeRsp_CreateTradeRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTradeRsp_CreateTradeRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTradeRsp_CreateTradeRspData) ProtoMessage() {}

func (x *CreateTradeRsp_CreateTradeRspData) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTradeRsp_CreateTradeRspData.ProtoReflect.Descriptor instead.
func (*CreateTradeRsp_CreateTradeRspData) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CreateTradeRsp_CreateTradeRspData) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type CancelTradeRsp_CancelTradeRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeNo string `protobuf:"bytes,1,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"` // 电商交易号
}

func (x *CancelTradeRsp_CancelTradeRspData) Reset() {
	*x = CancelTradeRsp_CancelTradeRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTradeRsp_CancelTradeRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTradeRsp_CancelTradeRspData) ProtoMessage() {}

func (x *CancelTradeRsp_CancelTradeRspData) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTradeRsp_CancelTradeRspData.ProtoReflect.Descriptor instead.
func (*CancelTradeRsp_CancelTradeRspData) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CancelTradeRsp_CancelTradeRspData) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

type GetTradeListRsp_GetTradeListRspData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TradeList []*TradeTrade `protobuf:"bytes,1,rep,name=trade_list,json=tradeList,proto3" json:"trade_list,omitempty"`
}

func (x *GetTradeListRsp_GetTradeListRspData) Reset() {
	*x = GetTradeListRsp_GetTradeListRspData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_trade_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTradeListRsp_GetTradeListRspData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeListRsp_GetTradeListRspData) ProtoMessage() {}

func (x *GetTradeListRsp_GetTradeListRspData) ProtoReflect() protoreflect.Message {
	mi := &file_order_trade_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeListRsp_GetTradeListRspData.ProtoReflect.Descriptor instead.
func (*GetTradeListRsp_GetTradeListRspData) Descriptor() ([]byte, []int) {
	return file_order_trade_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetTradeListRsp_GetTradeListRspData) GetTradeList() []*TradeTrade {
	if x != nil {
		return x.TradeList
	}
	return nil
}

var File_order_trade_proto protoreflect.FileDescriptor

var file_order_trade_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x12, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x66,
	0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x12, 0x26, 0x0a, 0x05,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0f,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4f, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x27, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x52, 0x05, 0x74, 0x72, 0x61, 0x64, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2f, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0x2b, 0x0a, 0x0e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x2f, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x4e, 0x6f, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x47, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x30, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x09, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x7a, 0x6c, 0x2d, 0x68, 0x65, 0x72, 0x65, 0x2f, 0x62, 0x74, 0x2d, 0x73, 0x68,
	0x6f, 0x70, 0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_trade_proto_rawDescOnce sync.Once
	file_order_trade_proto_rawDescData = file_order_trade_proto_rawDesc
)

func file_order_trade_proto_rawDescGZIP() []byte {
	file_order_trade_proto_rawDescOnce.Do(func() {
		file_order_trade_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_trade_proto_rawDescData)
	})
	return file_order_trade_proto_rawDescData
}

var file_order_trade_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_trade_proto_goTypes = []interface{}{
	(*TradeTrade)(nil),                          // 0: order.TradeTrade
	(*TradeOrder)(nil),                          // 1: order.TradeOrder
	(*CreateTradeReq)(nil),                      // 2: order.CreateTradeReq
	(*CreateTradeRsp)(nil),                      // 3: order.CreateTradeRsp
	(*CancelTradeReq)(nil),                      // 4: order.CancelTradeReq
	(*CancelTradeRsp)(nil),                      // 5: order.CancelTradeRsp
	(*GetTradeListReq)(nil),                     // 6: order.GetTradeListReq
	(*GetTradeListRsp)(nil),                     // 7: order.GetTradeListRsp
	(*CreateTradeRsp_CreateTradeRspData)(nil),   // 8: order.CreateTradeRsp.CreateTradeRspData
	(*CancelTradeRsp_CancelTradeRspData)(nil),   // 9: order.CancelTradeRsp.CancelTradeRspData
	(*GetTradeListRsp_GetTradeListRspData)(nil), // 10: order.GetTradeListRsp.GetTradeListRspData
	(*BaseTrade)(nil),                           // 11: order.BaseTrade
	(*BaseOrder)(nil),                           // 12: order.BaseOrder
	(*BaseOrderItem)(nil),                       // 13: order.BaseOrderItem
}
var file_order_trade_proto_depIdxs = []int32{
	11, // 0: order.TradeTrade.trade:type_name -> order.BaseTrade
	1,  // 1: order.TradeTrade.order_list:type_name -> order.TradeOrder
	12, // 2: order.TradeOrder.order:type_name -> order.BaseOrder
	13, // 3: order.TradeOrder.order_item_list:type_name -> order.BaseOrderItem
	0,  // 4: order.CreateTradeReq.trade:type_name -> order.TradeTrade
	8,  // 5: order.CreateTradeRsp.data:type_name -> order.CreateTradeRsp.CreateTradeRspData
	9,  // 6: order.CancelTradeRsp.data:type_name -> order.CancelTradeRsp.CancelTradeRspData
	10, // 7: order.GetTradeListRsp.data:type_name -> order.GetTradeListRsp.GetTradeListRspData
	0,  // 8: order.GetTradeListRsp.GetTradeListRspData.trade_list:type_name -> order.TradeTrade
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_trade_proto_init() }
func file_order_trade_proto_init() {
	if File_order_trade_proto != nil {
		return
	}
	file_order_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_order_trade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTradeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTradeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTradeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTradeListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTradeRsp_CreateTradeRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTradeRsp_CancelTradeRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_trade_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTradeListRsp_GetTradeListRspData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_trade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_trade_proto_goTypes,
		DependencyIndexes: file_order_trade_proto_depIdxs,
		MessageInfos:      file_order_trade_proto_msgTypes,
	}.Build()
	File_order_trade_proto = out.File
	file_order_trade_proto_rawDesc = nil
	file_order_trade_proto_goTypes = nil
	file_order_trade_proto_depIdxs = nil
}

var _ context.Context
